#!/bin/bash
# Auto-generated by create_job_list.py
# Array range matches clump_densitities (300 tasks). Do not edit by hand.
#SBATCH --account=def-vhenault
#SBATCH --job-name=clump_densitities
#SBATCH --cpus-per-task=1
#SBATCH --mem=3G
#SBATCH --time=00:10:00
#SBATCH --array=1-300
#SBATCH --output=logs/slurm-%A_%a.out
#SBATCH --error=logs/slurm-%A_%a.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mackenzie.hayduk@smu.ca

mkdir -p logs/clump_densitities
mkdir -p output/clump_densitities
module load gcc arrow

# Load environment
module load python/3.11
source /home/kenzhayd/projects/def-vhenault/kenzhayd/cbhbd_env/bin/activate

cd /home/kenzhayd/projects/def-vhenault/kenzhayd/cBHBd_IMBH_analysis

# Run the single model script, passing the SLURM Array Task ID
python single_model.py --task_id $SLURM_ARRAY_TASK_ID --jobs_file clump_densitities --output_dir output/clump_densitities
