"""
create_job_list.py

Description:
    Generates a parameter grid for  CBHBD cluster simulations 
    and exports it as a CSV job list. This script is designed to set up a SLURM array of models.

Outputs:
    - A CSV file (default: 'test.csv') containing a unique 'task_id' and the corresponding 
      parameter set for every combination in the generated grid.
    - A SLURM job script that runs the single_model.py script for each task in the array.

Note: Ensure your SLURM array range matches this total!

"""
import itertools
import csv
from pathlib import Path

# CONFIGURATION

job_list_name = "concentrations.csv"

# SLURM settings 
SLURM_ACCOUNT  = "def-vhenault"
SLURM_EMAIL    = "mackenzie.hayduk@smu.ca"
SLURM_TIME     = "00:10:00"
SLURM_MEM      = "3G"
MAX_CONCURRENT = None    # the %N in --array=1-N%M

# Model ICs
M0 = [1e7]
LOG_RHO = [5.62,6.62]  # 5.62 in Nolan's paper
RHO = [10 ** x for x in LOG_RHO]
Z_FEH = [-1.7]
RG = [26.25]
TEND = [3000]

# Ex, set this to range(1, 101) to run 100 seeds per configuration
SEEDS = range(1, 101) 

RANTALA_IMBH_SEED = [True]      # Toggle Rantala 2026 IMBH seed formation
CHATTOPADHYAY_SEED  = [False]   # Toggle Extended IMF
GALPY_POTENTIAL = [True]        # Toggle Galpy NFW Halo Potential
M_VIR = [1e9]                   # Virial mass used if galpy potential is enabled. 1e9 is default.
C_HALO = [5,7,9,12,17]                    # NFW Concentration parameter used if galpy potential is enabled. 7 is default. 

# Generate of runs grid
GRID = list(itertools.product(
    M0, RHO, Z_FEH, RG, TEND, SEEDS,
    RANTALA_IMBH_SEED, CHATTOPADHYAY_SEED , GALPY_POTENTIAL, M_VIR, C_HALO
))

N_TASKS = len(GRID)

# Write to jobs.csv
with open(job_list_name, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow([
        'task_id', 'M0', 'rhoh0', 'FeH', 'rg', 'tend', 'seed',
        'rantala_imbh_seed', 'chattopadhyay_seed', 'galpy_potential', 
        'M_vir', 'c_halo'
    ])
    for i, params in enumerate(GRID, 1):
        row = [i] + [str(p) for p in params]
        writer.writerow(row)

print(f"Generated {job_list_name} with {len(GRID)} total tasks.")


# Write the matching SLURM job script 
csv_path = Path(job_list_name)
job_script_path = csv_path.with_suffix('.sh')
concurrent = f"%{MAX_CONCURRENT}" if MAX_CONCURRENT else ""

job_script = f"""#!/bin/bash
# Auto-generated by create_job_list.py
# Array range matches {csv_path.name} ({N_TASKS} tasks). Do not edit by hand.
#SBATCH --account={SLURM_ACCOUNT}
#SBATCH --job-name={csv_path.stem}
#SBATCH --cpus-per-task=1
#SBATCH --mem={SLURM_MEM}
#SBATCH --time={SLURM_TIME}
#SBATCH --array=1-{N_TASKS}{concurrent}
#SBATCH --output=logs/slurm-%A_%a.out
#SBATCH --error=logs/slurm-%A_%a.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user={SLURM_EMAIL}

mkdir -p logs
mkdir -p output
module load gcc arrow

# Load environment
module load python/3.11
source /home/kenzhayd/projects/def-vhenault/kenzhayd/cbhbd_env/bin/activate

cd /home/kenzhayd/projects/def-vhenault/kenzhayd/cBHBd_IMBH_analysis

# Run the single model script, passing the SLURM Array Task ID
python single_model.py --task_id $SLURM_ARRAY_TASK_ID --jobs_file {csv_path.name} --output_dir output
"""

with open(job_script_path, 'w') as f:
    f.write(job_script)
job_script_path.chmod(0o755)  # make it executable

print(f"Generated {job_script_path} with --array=1-{N_TASKS}{concurrent} and --jobs_file {csv_path.name}.")

